### PR TITLE
Add lock around execution of Swagger codegen 'main'

### PR DESCRIPTION
**Pull request by chasup**
Adds a global lock around the executions of swagger codegen to prevent race conditions in the following scenario:

- Multi project build where the plugin is used multiple times
- Parallel builds enabled (./gradlew --parallel)

### CODE REVIEW

**Comment by int128** [comment]
Thank you for the contribution. LGTM!

**Comment by chasup** [comment]
You are most welcome! Could you give me a clue as to when you are likely to cut a release with this in (it will save me doing something horrid to work round the issue in a dependant project).

Cheers,
James.

**Comment by int128** [comment]
I have released 2.11.1. Please try it!

**Comment by chasup** [comment]
Looks good - thanks!

**Pull request merged**
